### ISSUE TITLE
TSLint support

### ISSUE THREAD

**Issue by vuki656** [jose-elias-alvarez/nvim-lsp-ts-utils#13]
Hey,

I'm not sure if you've taken any time to research support for TSLint but I thought to let you know its deprecated in favor of eslint (to become the "standard") so you probably shouldn't bother implementing it :)

**Comment by jose-elias-alvarez** [comment]
I personally agree, and since I've never actually used TSLint, I won't implement it myself. 

The reason I mentioned it is that TSLint deprecation is pretty recent (2019), so I imagine there's a good number of projects that are still using it. Since it supports CLI JSON output, it would be straightforward to implement TSLint support using the same strategy the plugin uses for ESLint (though the format of errors / fixes is different), so I'm definitely open to PRs. 

I'll leave this issue open to clarify that in case anyone's interested in tackling it.

**Comment by jose-elias-alvarez** [comment]
Update: I'm going to close this, since the scope of the plugin has changed a bit since the issue was opened. 

If anybody is interested in setting up TSLint diagnostics / code actions, I'd recommend using [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim), which can do both (parsing JSON is up to you, though). I'd consider merging a solid implementation into this plugin, but it's not something I'll work on otherwise.
