### ISSUE TITLE
default eslint config

### ISSUE THREAD

**Issue by elianiva** [jose-elias-alvarez/nvim-lsp-ts-utils#26]
hello! Is it possible to point to a default eslint config? I have a scratch folder where I like to play around with various languages so it's a mess and doesn't have a proper project structure, linter config, etc.

Is it possible to have a 'fallback' eslint config? Similar to [this](https://github.com/fsouza/prettierd#provide-default-configuration), thanks!

edit: the current behaviour is it throws this error if there's no eslint config in the current CWD.

```
Error executing vim.schedule lua callback: ...e/pack/packer/start/null-ls.nvim/lua/null-ls/helpers.lua:18: failed to decode json: Vim:E474: Unidentified byte: Error: No ESLint configuration found in /home/elianiva/dev/scratch
```

**Comment by jose-elias-alvarez** [comment]
The ideal behavior would be to use a local ESLint config file if it's present but fall back to a default otherwise, right? 

If so, it should be possible, since ESLint has a `--config` flag to specify the path to a config (annoyingly, it doesn't seem to work with `eslint_d`, but I'll open up an issue). We'd just have to check the root directory for a config file on setup and modify the arguments accordingly. You'd also have to modify your `tsserver` root directory settings to get it to attach in non-project directories, I think, but I imagine you've already done that if you're using a scratch folder.

From your error message, it looks like you're already using the null-ls integration, so I think I'll have the feature be a null-ls exclusive, since I want to move all the integrations to null-ls once it's a little more stable. I'll work on this and get back to you.

**Comment by elianiva** [comment]
> The ideal behavior would be to use a local ESLint config file if it's present but fall back to a default otherwise, right?

yep, I had similar thing when I was using EFM

> I think I'll have the feature be a null-ls exclusive, since I want to move all the integrations to null-ls once it's a little more stable

That sounds good to me (null-ls is super cool btw :)

**Comment by jose-elias-alvarez** [comment]
Thanks for the positive feedback! The plan is to have the `develop` branch of this plugin be null-ls-only in preparation for the move. I'll let you know once this specific feature is available there.

**Comment by jose-elias-alvarez** [comment]
The fallback functionality is available for ESLint and formatters on the `develop` branch, which also ripped out all of the non-null-ls code. Let me know how it works for you!

**Comment by jose-elias-alvarez** [comment]
Great! Going to close this for now, then. Feel free to open up another issue if you run into any issues.
