### ISSUE TITLE
ESLint config location troubles

### ISSUE THREAD

**Issue by VVKot** [jose-elias-alvarez/nvim-lsp-ts-utils#33]
Config location seems to be quite varied based on the project. In Typescript projects, the most common setup that I've seen is ESLint config near `package.json`, while `tsconfig.json` is in *sub*-folder called `src`, e.g. see https://github.com/microsoft/vscode. I would also argue that resolving near `package.json` is more appropriate than prioritizing the git root - but that also might be over-indexing on the projects I touched.

I wonder if it makes sense to have not only a string fallback with path to config, but also/instead accepting a callback so that users can themselves write a function that finds appropriate location?

Another alternative is simply search from the current file up to and including the git root until we find a config.

**Comment by VVKot** [comment]
Turns out eslint itself already does this bit:

> Another alternative is simply search from the current file up to and including the git root until we find a config.

So even though I get a log about eslint config not being found it works just fine. The true problem that I was facing is this: #34

**Comment by jose-elias-alvarez** [comment]
Even though your PR solved your issue, I'm actually going to re-open this as a reminder to work on:

1. Improving the ESLint "config not found" message, which can be misleading since, as you noted, ESLint does its own search, and
2. Allowing `eslint_config_fallback` to be a function, which I think is a great idea to handle more complex project structures.

**Comment by jose-elias-alvarez** [comment]
Closed in 3b8963d7bb15588e1a5e2fbd260f61a85c6e46e2 and 8360703781f88c3f49791e34d35d6868c3d222a1.
