### ISSUE TITLE
TSLspImportAll sometimes doesen't work

### ISSUE THREAD

**Issue by vuki656** [jose-elias-alvarez/nvim-lsp-ts-utils#37]
Hey, `TSLspImportAll` sometimes doesn't work for me. 

It's mostly when I have more than 1 missing import.

If it's just 1 it works as expected. 

https://user-images.githubusercontent.com/8104698/121735375-557db780-caf6-11eb-9b4c-4ab86cf687e9.mp4

**Comment by jose-elias-alvarez** [comment]
What happens if you run the command again without modifying the code? Does that help at all?

Anecdotally, I find that `tsserver` is pretty unreliable when it comes to code actions, even when using VS Code, but I'll investigate and see if there's anything I can do, since I have similar issues on my end.

**Comment by vuki656** [comment]
> What happens if you run the command again without modifying the code? Does that help at all?
> 
> Anecdotally, I find that `tsserver` is pretty unreliable when it comes to code actions, even when using VS Code, but I'll investigate and see if there's anything I can do, since I have similar issues on my end.

Same result. Nothing happens.

**Comment by jose-elias-alvarez** [comment]
Quick question: when you request code actions via `vim.lsp.buf.code_action()` at the missing import, is there actually a code action available to add the missing import? 

I'm playing around with this on a larger code base for work to see if I can specifically trigger failures, and I'm am finding that `tsserver` doesn't seem to reliably handle some libraries, even in VS Code (the code action simply isn't available for some imports).

**Comment by vuki656** [comment]
Yup tried multiple times and there are code actions available. Except for [yup](https://github.com/jquense/yup) but I don't get them in IntelliJ either.

Now that I was testing it again, I got it to work sometimes. Strange. Can't really spot a pattern.

**Comment by jose-elias-alvarez** [comment]
Got it. I'm also having trouble finding a pattern, but it's definitely true that it just doesn't work sometimes, even in a simple test environment. 

My tentative best guess is that `tsserver` LSP requests (especially when routed through `typescript-language-server` have a certain chance to fail, and since `TSLspImportAll` sends one request per missing import and needs them all to succeed (or at least return nothing), it's especially susceptible to failures. If that's the case, there's not much I can do, but I'll try to log a failure in the wild at work this week and see if there's issues anywhere else in the process.

**Comment by jose-elias-alvarez** [comment]
So I cleaned up the code a bit in dfdb635457cf277d0422cf4367eab3bd8dafd084 and fixed a possible issue where a loop was breaking early, but fundamentally, the issues are caused by `tsserver` randomly failing to return anything, which is why the issue is so inconsistent. I'm not sure what causes the failures the failures in the first place. I know that they occur occasionally when requesting code actions, even in VS Code, but they seem occur more frequently with this particular function, which leads me to believe that sending multiple requests back to back affects the failure rate. 

In 676508e13d373f6f3a2691e483cf037aef758ce5, I added a simple timer to stagger requests slightly, which seems to have a positive effect on the success rate (based on the results of running a shell script to repeat tests until failure, so more real-world testing is necessary). Still, since we can't really solve the fundamental issue, I also added a warning to at least give the user some feedback when requests time out. 

Let me know if these changes make a difference at all and if you have any other suggestions to improve the experience.

**Comment by vuki656** [comment]
Awesome, ill check it out and let you know how it works.

**Comment by vuki656** [comment]
Hey, finally got around to testing it. Definitely works more reliably now but still not perfect :D.

For example, [here](https://github.com/vuki656/campfire-web/blob/master/src/components/HomeNavHOC/HomeNavHOC.tsx), if you delete all imports, then run import all command, it will import everything except components, then if ran again, it will import all components.

**Comment by jose-elias-alvarez** [comment]
Good to hear! For the React issue: I don't know about the underlying mechanism, but I *think* this has to do with how `tsserver` handles React components. It seems like it always wants you to import `React` first, and it'll only import the components afterwards. 

When I clone your repo and run the equivalent VS Code action, it also requires me to run the command twice before it'll actually import everything, so I'm not sure how we can avoid this (apart from workarounds like running the command twice if the file is a `jsx` / `tsx` file).

**Comment by vuki656** [comment]
Sounds good.

Personally, I'm okay with importing it twice since I rarely have a use case where there are no imports and both component and function imports need to be added.

I'll close this since `ImportAll` works as expected now.

Thanks for the help.
