### ISSUE TITLE
Move consts/functions to the other existing files and update imports

### ISSUE THREAD

**Issue by non25** [jose-elias-alvarez/nvim-lsp-ts-utils#39]
Hi!
First of all, thanks a lot for this plugin, file rename is amazing. :slightly_smiling_face: 

In the codebase I'm working on there's multiple import options when I use code action, so if done automatically, it will most certainly mess things up by importing the wrong thing.

When refactoring, I usually move several functions, types and consts to the other file, and looks like I can't automatically move imports they use with them..

How can I help you implement that? :slightly_smiling_face:

**Comment by jose-elias-alvarez** [comment]
Hmm, I wonder – this behavior isn't part of the LSP specification, so there's only so much we can do. "Watching" exports would be very tricky, but I could potentially imagine hijacking the built-in `Move to a new file` code action to create a command to move an export from one open buffer into another and update references. You'd have to manually trigger it every time, though, but it could be useful. 

I've also thought about creating a version of `TSLspImportAll` that only adds imports if they're exported from an open buffer. That could help improve accuracy when automatically running code actions.

Let me know if either of those options sounds useful. Beyond that, I'll give it some thought, but since the plugin ultimately depends on LSP functionality, I'm not sure how close we can get to what you describe.

**Comment by non25** [comment]
Hijacking `Move to a new file` seems like the way to go. :slightly_smiling_face: 

I see following steps:

`df` - destination file which we want to move stuff to
`nf` - file created by `Move to a new file`

- Use `Move to a new file` to create `nf` in the same directory as `df`
- Move everything from `nf` to `df`
- Fix all imports in the opened and unsaved buffers that point to the `nf`
- Use reorganize imports or some sort of LSP-provided autofixing to possibly deduplicate imports in the `df` without importing anything new

As to `TSLspImportAll`, I think it will be much more useful if it could look for the imports in the opened buffers in addition to the exports, and prefer exports.
Because there could be imports like `EditIcon` from `common/icons`, but `common/icons` is not opened. And when you use autoimport, it could add it from something like `material` instead.

Maybe it would be wise to ask `tsserver` authors if it's a feature they would be interested in having. :thinking: 

Thanks for the response. :slightly_smiling_face:

**Comment by jose-elias-alvarez** [comment]
Right, I agree that ultimately big features like this should be implemented at the language server level. For the first idea, let me look into it some more and get back to you re: feasibility. For the second, I just opened up #42, so let me know there if you have any thoughts / ideas.

**Comment by jose-elias-alvarez** [comment]
So I looked into this, and my conclusion is that I'm not at all confident we could do this in a way that would a) provide a good user experience, and b) not break all the time. It's a cool idea, but ultimately it's too far from LSP behavior to implement in a satisfactory way. 

For the priority idea, I've put together an implementation in #43 that implements your ideas, so let me know if you have any feedback there.

**Comment by non25** [comment]
How do you approach the problem of moving functions between files and updating imports? :thinking: 
Is there some solution which I'm not aware of, or do you update imports by hand like I'm doing currently?

**Comment by jose-elias-alvarez** [comment]
Honestly I'm not sure if there is a better solution than just doing it manually (if there is, I'd love to know, too). I've only worked with Neovim and VS Code, but as far as I know, there's no editor / extension that has that kind of functionality. 

Your question gave me an idea: I could create a new function to detect broken imports from `tsserver` diagnostics, delete them, and run `:TSLspImportAll`. It would then be possible to either run the function manually or set it up so that it runs automatically when opening / focusing a buffer. This wouldn't be as convenient as fully automated updates, but it would take away some of the pain from going through the project and updating broken imports. 

Let me know if you'd be interested in that and I can put something together.

**Comment by non25** [comment]
That sounds really cool. I'd love to test something like that.

The only thing that makes me avoid using `:TSLspImportAll` in existing files is that it reorders imports, thus making extra noise in diffs when merging. :thinking: 

I use it all the time in the new files though.

Also could we batch interactive import selection? I would imagine if we run `:TSLspImportAll` for a 10 files, every time there will be options to import from?


What do you think about this workflow:

1. move const/function to the other file, save both
2. hover on moved const/function and type use something like `:TSLspPointBrokenImportsHere`
3. profit? :grin: 

Can we get import path from `tsserver` by hovering on a const/function?

Cases where we already have grouped import might be annoying to deal with though. :thinking: 


Another way which comes to mind:

1. save a list of references to a hovered const/function somewhere
2. move it to the other file by hand
3. update imports from that list using some mechanism like `:TSLspImportAll`

Thanks. :slightly_smiling_face:

**Comment by jose-elias-alvarez** [comment]
Batching imports is possible. I could make it possible to specify the buffer(s) you want to run it on, e.g. `:TSLspImportAll App.tsx`, or run it on all open buffers via something like `:TSLspImportAll all`. 

I don't think it's possible to request an import path from `tsserver`, but saving references is a really interesting idea. I think the most reliable way to do this would be to make sure all the files that refer to the moved function are loaded, then run `:TSLspFixBrokenImports` (or whatever we decide to call it) on each. 

I opened #46, #47, and #48 to discuss potential improvements, so we can talk more there if you have more ideas.

**Comment by non25** [comment]
Can we somehow run regular code action on a const/function with missing import?

For example, when I import a const/function from a file, which is already used for some imports `tsserver` says this:
> `Add 'someFunction' to existing import declaration from "somepath"`

And by doing it this way I never produce noisy diffs. :thinking: 
Would be cool to use this automagically for fixing several files though. Could it work with saved references?

**Comment by jose-elias-alvarez** [comment]
I'm not sure I understand completely, but `:TSLspImportAll` simply gets and runs code actions, so if that's the available code action, that's what it'll do. The issue is that when it adds two or more imports from the same source, each code action is (at that point) independent, so each import will get a separate import statement. 

I'm not that thrilled with the current need to organize imports afterwards (and it's not how VS Code does it), but manually merging imports is complicated, and when we can completely offload that complexity to `tsserver`, I prefer to do so. I'll see if I can think of something else though.
