### ISSUE TITLE
ImportAll seems not working

### ISSUE THREAD

**Issue by miladabc** [jose-elias-alvarez/nvim-lsp-ts-utils#4]
Thanks for your great functions.
`RenameFile` and `Organize` commands work like a charm but `ImportAll` and `FixCurrent` do not.
Also they don't output any error, any idea where to look for problem?

**Comment by jose-elias-alvarez** [comment]
Thanks for the feedback! `ImportAll` and `FixCurrent` are a bit unreliable and can sometimes take multiple tries before they do what they're supposed to, especially on larger projects. I believe this is because `buf_request_sync` is more likely to time out when the language server has to go through a lot of files. (I also think `tsserver` itself has issues with larger projects, since I sometimes see similar behavior when using VS Code.) 

In the near future, I want to refactor these to be asynchronous, which should solve the issue more thoroughly (and improve performance). For now, though, I've just pushed a commit that increases the timeout and adds a message if the language server doesn't send a response back in time (or sends an empty response). Could you let me know if the functions work for you now?

**Comment by jose-elias-alvarez** [comment]
Update: `FixCurrent and `ImportAll` are both async now. The former should work out-of-the-box, but the latter depends on [plenary.nvim](https://github.com/nvim-lua/plenary.nvim) (it'll fall back to the sync implementation if plenary isn't available). 

They should both be more reliable, but let me know how everything is working on your end.

**Comment by miladabc** [comment]
Yep works perfectly fine now, thanks.

**Comment by jose-elias-alvarez** [comment]
Thanks for the confirmation!
