### ISSUE TITLE
Add function to save and update references 

### ISSUE THREAD

**Issue by jose-elias-alvarez** [jose-elias-alvarez/nvim-lsp-ts-utils#48]
@non25 suggests a refactoring workflow where you could:

>  
    1. save a list of references to a hovered const/function somewhere
    2. move it to the other file by hand
    3. update imports from that list using some mechanism like :TSLspImportAll

I think this would work well with #46 and #47.

**Comment by non25** [comment]
I like this because it is explicit.

Here's more refined version:

1. Hover on const/function
2. Run `:TSLspMovePrepare`, it will save references
3. Move const/function to the other file, save it and hover on it
4. Run `:TSLspMoveDone`, it will open all buffers with references and run import code action on references, if there is more than one import option - it will use one which matches current file path

What do you think? :thinking:

**Comment by jose-elias-alvarez** [comment]
I like it. If we require the user to specifically move to the relevant const / function, we could save multiple sets of references in state to allow moving multiple exports at the same time, too.

**Comment by non25** [comment]
Which one you like better, this one or #46 ? :slightly_smiling_face: 

I did this workflow manually for a few times this week.
Opened reference list as a quickfix, moved function and fixed them one by one. Silly me. :grin:

**Comment by jose-elias-alvarez** [comment]
I think we should implement them both, since I imagine we'd want this functionality to build on a more general "fix broken imports" function. Will hopefully have time to work on it this week.

**Comment by jose-elias-alvarez** [comment]
Like the other issues I've been closing, this is a cool idea but should be implemented at the language server level. The whole point of the LSP specification is to make things like this editor-independent, so even though we could implement a Neovim-specific version, I'd rather put that effort into adding something that everyone can benefit from.
